2025-02-08 12:19:58.256736 - Error: name 'QProgressDialog' is not defined
Function: run_script
Stack Trace:
Traceback (most recent call last):
  File "C:\Users\90544\PycharmProjects\health-check-report\main.py", line 2055, in run_scripts_and_export
    pdf_path = self.generate_pdf_report(output_path, output_dir, valid_username, rundate)
  File "C:\Users\90544\PycharmProjects\health-check-report\main.py", line 1581, in generate_pdf_report
    progress_dialog = QProgressDialog("PDF oluşturuluyor, lütfen bekleyin...", None, 0, 0, self)
NameError: name 'QProgressDialog' is not defined


2025-02-08 12:42:58.649429 - Error: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Must declare the scalar variable "@xpCmdShellEnabled". (137) (SQLExecDirectW); [42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Must declare the scalar variable "@xpCmdShellEnabled". (137); [42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Must declare the scalar variable "@xpCmdShellEnabled". (137)')
Function: SQL Execution Error
Stack Trace:
Traceback (most recent call last):
  File "C:\Users\90544\PycharmProjects\health-check-report\main.py", line 2004, in run_scripts_and_export
    cursor.execute(statement)
pyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Must declare the scalar variable "@xpCmdShellEnabled". (137) (SQLExecDirectW); [42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Must declare the scalar variable "@xpCmdShellEnabled". (137); [42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Must declare the scalar variable "@xpCmdShellEnabled". (137)')


2025-02-08 12:42:58.650946 - Error: ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name '#PowerShellOutput'. (208) (SQLExecDirectW)")
Function: windows_group_error
Stack Trace:
Traceback (most recent call last):
  File "C:\Users\90544\PycharmProjects\health-check-report\main.py", line 2019, in run_scripts_and_export
    cursor.execute(select)
pyodbc.ProgrammingError: ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name '#PowerShellOutput'. (208) (SQLExecDirectW)")


2025-02-08 12:42:58.997445 - Error: ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot drop the table '#SystemDrive', because it does not exist or you do not have permission. (3701) (SQLExecDirectW)")
Function: SQL Execution Error
Stack Trace:
Traceback (most recent call last):
  File "C:\Users\90544\PycharmProjects\health-check-report\main.py", line 2004, in run_scripts_and_export
    cursor.execute(statement)
pyodbc.ProgrammingError: ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot drop the table '#SystemDrive', because it does not exist or you do not have permission. (3701) (SQLExecDirectW)")


2025-02-08 12:43:01.718114 - Error: Worksheet named 'SystemDrive' not found
Function: SQLFiles
Stack Trace:
Traceback (most recent call last):
  File "C:\Users\90544\PycharmProjects\health-check-report\main.py", line 862, in generate_dataframe_from_excel
    SystemDrive = pd.read_excel(excel_data, sheet_name="SystemDrive")
  File "C:\Users\90544\PycharmProjects\lab\health-check-report\lib\site-packages\pandas\io\excel\_base.py", line 508, in read_excel
    data = io.parse(
  File "C:\Users\90544\PycharmProjects\lab\health-check-report\lib\site-packages\pandas\io\excel\_base.py", line 1616, in parse
    return self._reader.parse(
  File "C:\Users\90544\PycharmProjects\lab\health-check-report\lib\site-packages\pandas\io\excel\_base.py", line 773, in parse
    sheet = self.get_sheet_by_name(asheetname)
  File "C:\Users\90544\PycharmProjects\lab\health-check-report\lib\site-packages\pandas\io\excel\_openpyxl.py", line 582, in get_sheet_by_name
    self.raise_if_bad_sheet_by_name(name)
  File "C:\Users\90544\PycharmProjects\lab\health-check-report\lib\site-packages\pandas\io\excel\_base.py", line 624, in raise_if_bad_sheet_by_name
    raise ValueError(f"Worksheet named '{name}' not found")
ValueError: Worksheet named 'SystemDrive' not found


